// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBTCugmnpaUYkns6npOV0FQ06DDyyBxb4',
    appId: '1:326121250288:web:cd7062be3324c44b61d135',
    messagingSenderId: '326121250288',
    projectId: 'fasum-app-64936',
    authDomain: 'fasum-app-64936.firebaseapp.com',
    storageBucket: 'fasum-app-64936.firebasestorage.app',
    measurementId: 'G-DQNYP48JG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoC4Wj1CbeejHx0PVOpjDxuOsSygURuFc',
    appId: '1:326121250288:android:271f9d438323a90b61d135',
    messagingSenderId: '326121250288',
    projectId: 'fasum-app-64936',
    storageBucket: 'fasum-app-64936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpI4EHF3s5KfEE6lKTk2rJ0Xix68djP4M',
    appId: '1:326121250288:ios:409cecc13feb9c6d61d135',
    messagingSenderId: '326121250288',
    projectId: 'fasum-app-64936',
    storageBucket: 'fasum-app-64936.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpI4EHF3s5KfEE6lKTk2rJ0Xix68djP4M',
    appId: '1:326121250288:ios:409cecc13feb9c6d61d135',
    messagingSenderId: '326121250288',
    projectId: 'fasum-app-64936',
    storageBucket: 'fasum-app-64936.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBTCugmnpaUYkns6npOV0FQ06DDyyBxb4',
    appId: '1:326121250288:web:eeb1bdac78dde40d61d135',
    messagingSenderId: '326121250288',
    projectId: 'fasum-app-64936',
    authDomain: 'fasum-app-64936.firebaseapp.com',
    storageBucket: 'fasum-app-64936.firebasestorage.app',
    measurementId: 'G-YQJ41WND6L',
  );
}
