// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgijzjPUA_wBP1uX-pg95m5F3DiCQetr4',
    appId: '1:1058215506499:web:444b357c396d90bf1b5af6',
    messagingSenderId: '1058215506499',
    projectId: 'fasum-app-336a6',
    authDomain: 'fasum-app-336a6.firebaseapp.com',
    storageBucket: 'fasum-app-336a6.firebasestorage.app',
    measurementId: 'G-DBLCZK8K4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlllpU33R4HRSl0lQzzQQ6P6x9LlOyETU',
    appId: '1:1058215506499:android:6dbde61117089c1d1b5af6',
    messagingSenderId: '1058215506499',
    projectId: 'fasum-app-336a6',
    storageBucket: 'fasum-app-336a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0-nhfSjGj-_GSggJEZYua43gLSZHPXE',
    appId: '1:1058215506499:ios:d9c3acddd22a01311b5af6',
    messagingSenderId: '1058215506499',
    projectId: 'fasum-app-336a6',
    storageBucket: 'fasum-app-336a6.firebasestorage.app',
    iosBundleId: 'com.example.fasumTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0-nhfSjGj-_GSggJEZYua43gLSZHPXE',
    appId: '1:1058215506499:ios:d9c3acddd22a01311b5af6',
    messagingSenderId: '1058215506499',
    projectId: 'fasum-app-336a6',
    storageBucket: 'fasum-app-336a6.firebasestorage.app',
    iosBundleId: 'com.example.fasumTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgijzjPUA_wBP1uX-pg95m5F3DiCQetr4',
    appId: '1:1058215506499:web:9819d2e8aa724b7f1b5af6',
    messagingSenderId: '1058215506499',
    projectId: 'fasum-app-336a6',
    authDomain: 'fasum-app-336a6.firebaseapp.com',
    storageBucket: 'fasum-app-336a6.firebasestorage.app',
    measurementId: 'G-HT1126E5WP',
  );
}
