name: fasum_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  geolocator: ^14.0.0
  cloud_firestore: ^5.6.6
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fasum_icon_512.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/fasum_icon.png
    - assets/fasum_icon_512.png

